# Generated by Django 4.1.2 on 2022-11-15 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(max_length=100, null=True, verbose_name='Опыт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('title', models.CharField(max_length=100, verbose_name='Наименование вакансии')),
                ('salary_level', models.FloatField(null=True, verbose_name='Уровень зарплаты')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание вакансии')),
                ('is_public', models.BooleanField(default=False, verbose_name='Не опубликовано')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='vacancies.experience', verbose_name='Опыт')),
            ],
        ),
    ]
