# Generated by Django 4.1.2 on 2022-11-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='educational_institution',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='place_of_work',
        ),
        migrations.AddField(
            model_name='course',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cources', to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resumes.resume', verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resumes.resume', verbose_name='Резюме'),
        ),
    ]
