# Generated by Django 4.1.2 on 2022-11-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_resume_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Не опубликовано'),
        ),
    ]
