# Generated by Django 4.1.2 on 2022-11-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_response_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='vacancy',
        ),
    ]
