# Generated by Django 4.1.2 on 2022-11-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0013_response_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='message',
        ),
        migrations.AddField(
            model_name='response',
            name='hello_message',
            field=models.TextField(blank=True, default='Здравствуйте. Нас заинтересовало ваше резюме!', max_length=3000, verbose_name='Приветственное сообщение'),
        ),
    ]
